spring:
  datasource:
    driverClassName: org.h2.Driver
    generate-unique-name: true
    url: jdbc:h2:mem:testing;MODE=MySQL

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
